version: '3.8'

services:
  # Клиентское приложение Xitter
  xitter-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Для разработки можно раскомментировать следующие строки
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public

  # Заглушка для API сервера
  # xitter-api:
  #   image: node:18-alpine
  #   command: sh -c "echo 'API server placeholder' && sleep infinity"
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped 
